language: rust
rust:
  - 1.41.0
os:
  - linux
  - osx
  - windows
rust:
  - stable
matrix:
  fast_finish: true
before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo install --force cargo-audit  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo generate-lockfile            ; fi
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo audit ; fi
  - cargo test --verbose
